### ISSUE TITLE
CheckBox

### ISSUE THREAD

**Issue by webfalter** [OFFLINE-GmbH/oc-forms-plugin#1]
Wie kann man eine CheckBox als Formular Inhalt hinzufügen ?

**Comment by tobias-kuendig** [comment]
Feel free to submit a PR. This could be implemented as a new type under `input`:

https://github.com/OFFLINE-GmbH/oc-forms-plugin/blob/d4d9107d72670c34dc06bb69b11312aa43ae4dd6/models/form/fields.yaml#L26

Of course, the new type would have to be handled correctly in lists, forms and the mail views.

**Comment by tobias-kuendig** [comment]
You can create a checkbox list with just a single checkbox.
